//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.18 at 06:48:02 AM IST 
//


package com.poc.userprofile.schemas.userprofile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GetUserProfile" type="{http://www.example.com/xml/getuser}GetUserProfile"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getUserProfile"
})
@XmlRootElement(name = "GetUserProfileResponse", namespace = "http://www.example.com/xml/getuser")
public class GetUserProfileResponse {

    @XmlElement(name = "GetUserProfile", namespace = "http://www.example.com/xml/getuser", required = true)
    protected GetUserProfile getUserProfile;

    /**
     * Gets the value of the getUserProfile property.
     * 
     * @return
     *     possible object is
     *     {@link GetUserProfile }
     *     
     */
    public GetUserProfile getGetUserProfile() {
        return getUserProfile;
    }

    /**
     * Sets the value of the getUserProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetUserProfile }
     *     
     */
    public void setGetUserProfile(GetUserProfile value) {
        this.getUserProfile = value;
    }

}
