//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.18 at 06:48:02 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.com/xml/newuser", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.poc.userprofile.schemas.userprofile;
